services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "8082:5678"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:


# you can also use it with postgres insted of sqlite
# https://docs.n8n.io/reference/docker/#postgres-configuration

# here is docker-compose example
# https://docs.n8n.io/reference/docker/#docker-compose


# docker volume create n8n_data

# docker run -it --rm \
#  --name n8n \
#  -p 5678:5678 \
#  -e DB_TYPE=postgresdb \
#  -e DB_POSTGRESDB_DATABASE=<POSTGRES_DATABASE> \
#  -e DB_POSTGRESDB_HOST=<POSTGRES_HOST> \
#  -e DB_POSTGRESDB_PORT=<POSTGRES_PORT> \
#  -e DB_POSTGRESDB_USER=<POSTGRES_USER> \
#  -e DB_POSTGRESDB_SCHEMA=<POSTGRES_SCHEMA> \
#  -e DB_POSTGRESDB_PASSWORD=<POSTGRES_PASSWORD> \
#  -v n8n_data:/home/node/.n8n \
#  docker.n8n.io/n8nio/n8n