services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_DATA_PATH:-postgres_data}:/var/lib/postgresql/data
    networks:
      - keycloak-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: ${KEYCLOAK_CONTAINER_NAME:-keycloak}
    command:
      - start
      - --proxy edge
      - --hostname-strict=${KEYCLOAK_HOSTNAME_STRICT:-false}
      - --hostname-strict-https=${KEYCLOAK_HOSTNAME_STRICT_HTTPS:-false}
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${POSTGRES_CONTAINER_NAME:-postgres}/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_PROXY: edge
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: ${NGINX_CONTAINER_NAME:-nginx}
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ${NGINX_CONF_PATH:-./nginx/conf.d}:/etc/nginx/conf.d
      - ${CERTBOT_CONF_PATH:-./certbot/conf}:/etc/letsencrypt
      - ${CERTBOT_WWW_PATH:-./certbot/www}:/var/www/certbot
    networks:
      - keycloak-network
    restart: unless-stopped
    depends_on:
      keycloak:
        condition: service_healthy
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  certbot:
    image: certbot/certbot:latest
    container_name: ${CERTBOT_CONTAINER_NAME:-certbot}
    volumes:
      - ${CERTBOT_CONF_PATH:-./certbot/conf}:/etc/letsencrypt
      - ${CERTBOT_WWW_PATH:-./certbot/www}:/var/www/certbot
    restart: unless-stopped
    depends_on:
      nginx:
        condition: service_healthy
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  ${POSTGRES_DATA_PATH:-postgres_data}:

networks:
  keycloak-network:
    name: ${KEYCLOAK_NETWORK_NAME:-keycloak-network}