services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${TOKEN}
    environment:
      - TOKEN=${TOKEN}
    restart: unless-stopped
    network_mode: host # this is a must to access localhost from the main macOS host