services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: 'your_master_key_here'
      MEILI_ENV: 'development'
      MEILI_NO_ANALYTICS: 'true'
    volumes:
      - ./data.ms:/meili_data

volumes:
  meili_data:
