services:
  strapi-postgres:
    image: postgres:latest
    container_name: strapi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - strapi_postgres_data:/var/lib/postgresql/data

volumes:
  strapi_postgres_data: